### ISSUE TITLE
System for identifying "pre-order only" items. 

### ISSUE THREAD

**Issue by generalludd** [fsmn/plantsale#85]
Need away to identify plants that are not sold at the physical sale, but are pre-order only so they can't be added to the wish list. These items can be ordered at a woo-commerce site and picked up curb-side at the sale. This value needs to be available to the public site so that these items will be appropriately identified.

**Comment by lnewmanheggie** [comment]
Has this been done yet? If not I can look into it.

**Comment by generalludd** [comment]
@lnewmanheggie This has actually been completed. We chose to take a different approach. We use a value "flat_exclude" on orders. This is one of the more arcane aspects of the plant sale's organizational logic. They do the sale well (obviously), but one of the programming challenges has been finding efficient ways to elegantly meet these requirements so the system remains flexible and stable.
