### ISSUE TITLE
Printable reports

### ISSUE THREAD

**Issue by generalludd** [fsmn/plantsale#96]
Convert reports to printable versions instead of requiring they be imported into Filemaker
[shelf checking sheets 2019.pdf](https://github.com/fsmn/plantsale/files/5740589/shelf.checking.sheets.2019.pdf)
[inventory 2019 no bulbs.pdf](https://github.com/fsmn/plantsale/files/5740590/inventory.2019.no.bulbs.pdf)

**Comment by generalludd** [comment]
@lnewmanheggie maybe we can look at this to discuss how to approach this. It would be good to have this. It's become a priority. It will involve creating views, css styles, and figuring out a way to tie it into the existing Order searching system. (order.php search())

**Comment by lnewmanheggie** [comment]
Great! I would love to work on this.

**Comment by generalludd** [comment]
Add catalog number on inventory report again between pot size and wed rec'd

**Comment by generalludd** [comment]
@lnewmanheggie I have fixed the printing issue. It required that I set all css files to media="screen" except the print.css (which I kept as media="print" I also set table widths to be 10.5in. I made some other changes and pushed this up. Please pull the branch before continuing work.

**Comment by generalludd** [comment]
Also, I have merged the work you've done to main so Pat can start testing this out. Keep working on your branch, though. There may be more changes we'll need to make.

**Comment by lnewmanheggie** [comment]
Great! will do.

**Comment by lnewmanheggie** [comment]
I think this change makes the comments column slightly bigger. Added a max-width property to td in the printable css.
